chat.print("It all started as")
time.sleep(2.5)
chat.print("I dicided to travel")
time.sleep(2.5)
chat.print("to my Grandma...")
time.sleep(5)
chat.print("My Grandma lives on")
time.sleep(2.5)
chat.print("the Island of Port")
time.sleep(2.5)
chat.print("Neightbour. However")
time.sleep(2.5)
chat.print("its a long travel..")
time.sleep(2.5)
chat.print("and only possible by ship...")
time.sleep(5)
chat.print("At first it was nice and silent.")
time.sleep(2.5)
chat.print("Too silent for me...")
time.sleep(5)
chat.print("And my feeling was right...")
time.sleep(2.5)
chat.print("Freaking right!")
time.sleep(5)
chat.print("<Sailor A> \"Did you hear that?\"")
time.sleep(2.5)
chat.print("<Sailor B> \"What?\"")
time.sleep(2.5)
chat.print("<Sailor A> \"That noise...\"")
time.sleep(2.5)
chat.print("<Sailor B> \"Huh? What was that?\"")
time.sleep(3.5)
chat.print("<Sailor A, Sailor B and Watcher> \"What is that fog???\"")
effect.setFogDensity(0,20)
time.sleep(2.5)
chat.print("<Watcher> \"I can´t see anything in this fog!\"")
time.sleep(2.5)
chat.print("<Watcher> \"Oh no...\"")
time.sleep(3)
chat.print("<Watcher> \"WE´RE GOING TO CRASH!!!\"")